openapi: 3.0.3
info:
  title: Bank Argent API Documentation
  description: |-
    Contains a proposal for Phase 2 routes.
  termsOfService: http://swagger.io/terms/
  version: 1.0.0
tags:
  - name: transaction
    description: Everything about transactions
paths:
  /user/transaction/{monthId}:
    get:
      tags:
        - transaction
      summary: View all the transactions of the current month
      description: View all the transactions of the current month
      operationId: getAllTransactions
      parameters:
        - name: monthId
          in: path
          description: ID of the current month
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'          
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '400':
          description: Invalid status value
      security:
      - jwt_auth: []
  /user/transaction/{transactionId}:
    get:
      tags:
        - transaction
      summary: Find transaction by ID
      description: Returns the details of one particular transaction
      operationId: getTransactionById
      parameters:
        - name: transactionId
          in: path
          description: ID of transaction to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Invalid ID supplied
        '404':
          description: Transaction not found
      security:
      - jwt_auth: []
  /user/transaction/{transactionId}/{informationId}:
    post:
      tags:
        - transaction
      summary: Add a particular information inside a particular transaction
      description: Add a particular information inside a particular transaction
      operationId: addInformationInTransaction
      parameters:
      - name: transactionId
        in: path
        description: ID of the transaction containing the particular information to add
        required: true
        schema:
          type: integer
          format: int64
      - name: informationId
        in: path
        description: ID of an information that needs to be added
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Information'
          application/xml:
            schema:
              $ref: '#/components/schemas/Information'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'          
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: Transaction or information not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'          
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
      - jwt_auth: []
    delete:
      tags:
        - transaction
      summary: Deletes a particular information from a particular transaction
      description: deletes a particular information from a particular transaction
      operationId: deleteInformation
      parameters:
        - name: informationId
          in: path
          description: Information id to delete
          required: true
          schema:
            type: integer
            format: int64
        - name: transactionId
          in: path
          description: Transaction id containing the information to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Invalid information or transaction value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'          
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
      - jwt_auth: []
    put:
      tags:
        - transaction
      summary: Updates a particular information from a particular transaction
      description: Updates a particular information from a particular transaction
      operationId: updateInformation
      parameters:
        - name: informationId
          in: path
          description: Information id to update
          required: true
          schema:
            type: integer
            format: int64
        - name: transactionId
          in: path
          description: Transaction id containing the information to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:  # Updated to accept an Information object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Information'
          application/xml:
            schema:
              $ref: '#/components/schemas/Information'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Invalid information or transaction value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'          
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
      - jwt_auth: []
  
components:
  schemas:
    Transaction:
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 13
        information:
          type: array
          items:
            $ref: '#/components/schemas/Information'
      description: Represents a transaction
    Information:
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 03
        details:
          type: string
      description: Represents information related to a transaction
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      xml:
        name: '##default'
  requestBodies:
    Transaction:
      description: Transaction object that needs to be added or updated
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Transaction'
        application/xml:
          schema:
            $ref: '#/components/schemas/Transaction'
    
  securitySchemes:
    jwt_auth:
      type: apiKey
      name: Authorization
      in: header