openapi: 3.0.3
info:
  title: Bank Argent API Documentation
  description: |-
    Contains a proposal for Phase 2 routes.
  termsOfService: http://swagger.io/terms/
  version: 1.0.0
tags:
  - name: transaction
    description: Everything about transactions
paths:
  /user/transaction:
    get:
      tags:
        - transaction
      summary: View all the transactions of the current month
      description: View all the transactions of the current month
                   Requires JWT Authorization header for user authentication
      operationId: getAllTransactions
      parameters:
        - name: monthId
          in: query
          description: ID of the current month
          required: true
          schema:
            $ref: '#/components/schemas/Month'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'          
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '400':
          description: Invalid status value
      security:
      - jwt_auth: []
  /user/transaction/{transactionId}:
    get:
      tags:
        - transaction
      summary: Find transaction by ID
      description: Returns the details of one particular transaction
                   Requires JWT Authorization header for user authentication
      operationId: getTransactionById
      parameters:
        - name: transactionId
          in: path
          description: ID of transaction to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Invalid ID supplied
        '404':
          description: Transaction not found
      security:
      - jwt_auth: []
  /user/transaction/{transactionId}/update:
    put:
      tags:
        - transaction
      summary: Updates, deletes or creates an information from a particular transaction
      description: Updates a particular information from a particular transaction
                   Requires JWT Authorization header for user authentication
      operationId: updateInformation
      parameters:
        - name: transactionId
          in: path
          description: Transaction id containing the information to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:  # Updated to accept an Information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
          application/xml:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  category:
                    type: string
            application/xml:
              schema:
                type: object
                properties:
                  category:
                    type: string
        '400':
          description: Invalid transaction value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'          
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
      - jwt_auth: []
  
components:
  schemas:
    Transaction:
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 13
        category:
          type: string
          description: Category of the transaction
      description: Represents a transaction
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      xml:
        name: '##default'
    Month:
      type: object
      properties:
        monthId:
          type: integer
          format: int64
          example: 11
      description: Represents a month
  requestBodies:
    Transaction:
      description: Transaction object that needs to be added or updated
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Transaction'
        application/xml:
          schema:
            $ref: '#/components/schemas/Transaction'
  securitySchemes:
    jwt_auth:
      type: apiKey
      name: Authorization
      in: header
      description: JWT Authorization header for user authentication
security:
    - jwt_auth: []